version: '3.8'

services:
  web:
    image: php:8.3-apache
    container_name: phpBiblio
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./apache2/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    ports:
      - "8082:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysqlBiblio
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblio
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminBiblio
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

